name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use a compatible Node.js version
          cache: 'yarn'

      # Step 3: Install dependencies with Yarn
      - name: Install dependencies
        run: yarn install

      # Step 4: Build the Vite project
      - name: Build project
        run: yarn build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
